inference:
  ros__parameters:
    detector:
      engine_path:
        "/home/docker/ros2_ws/src/inference_ros2/model/yolov8-keypoint-det-cropweed-nuc-fp32-23.10.engine"
      image_topic:
        "/sensors/zed_laser_module/zed_node/rgb/image_rect_color/compressed"
    depth_estimation:
      depth_image_topic:
        "/sensors/zed_laser_module/zed_node/depth/depth_registered"
      camera_info_topic:
        "/sensors/zed_laser_module/zed_node/rgb_gray/camera_info"
      use_depth: true
      depth_sample_size: 5
      camera_height: 1.0
      camera_tilt: 30.0
